# Generated by Django 3.0.3 on 2020-02-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="Difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Veryeasy"),
                    (2, "Easy"),
                    (3, "Normal"),
                    (4, "Hard"),
                    (5, "Challenging"),
                ],
                default=3,
            ),
        ),
    ]
