# Generated by Django 3.0.3 on 2020-02-26 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("qb", "0003_auto_20200226_0612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date_published"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
